/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test.app

import java.util.*
import kotlin.system.exitProcess

fun main() {
    val scanner = Scanner(System.`in`)
    var isExit = false
    var validation = Validation()

    while (!isExit) {
        val rawInput = scanner.nextLine()
        val strs = rawInput.split(" ").toTypedArray()

        when (strs[0]) {
            "login" -> validation.attempLogin(strs[1])
            "logout" -> validation.doLogout()
            "deposit" -> {
                if(!strs[1].isNumber()) break
                validation.doDeposit(strs[1].toInt())
            }
            "withdraw" -> {
                if(!strs[1].isNumber()) break
                validation.doWithDraw(strs[1].toInt())
            }
            "transfer" -> {
                if(!strs[2].isNumber()) break
                validation.doTransfer(strs[1],strs[2].toInt())
            }
            "exit" -> exitProcess(0)

            else -> println("Invalid command")
        }
    }
}

