/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test.app

class MessageUtils {

    fun helloMessages(name: String) {
        println("Hello, welcome $name!");
    }

    fun currentBalanceMessages(balance: Int) {
        println("Your balance $$balance")
    }

    fun transferMessages(balance: Int, name: String) {
        println("Transferred $$balance to $name")
    }

    fun oweMessages(balance: Int, name: String, isFrom: Boolean) {
        if(isFrom) {
            println("Owed $$balance from $name");
        } else {
            println("Owed $$balance to $name");
        }
    }

    fun goodbyMessages(name: String) {
        println("goodby $name")
    }
}
