/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package test.app

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.io.ByteArrayOutputStream
import java.io.PrintStream


class MessageUtilsTest {

    private val outputStreamCaptor: ByteArrayOutputStream = ByteArrayOutputStream()
    private val messagesUtils = MessageUtils()

    @BeforeEach
    fun setUp() {
        System.setOut(PrintStream(outputStreamCaptor))
    }

    @Test
    fun helloMessages_test() {
        val name = "raldes"
        messagesUtils.helloMessages(name)
        val splitName = outputStreamCaptor.toString().split("\n".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
        assertEquals("Hello, welcome $name!", splitName[0].trim())
    }

    @Test
    fun currentBalanceMessages_test() {
        val balance = 0;
        messagesUtils.currentBalanceMessages(balance)
        val splitName = outputStreamCaptor.toString().split("\n".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
        assertEquals("Your balance \$$balance", splitName[0].trim())
    }

    @Test
    fun goodbyMessages_test() {
        val name = "raldes"
        messagesUtils.goodbyMessages(name)
        val splitName = outputStreamCaptor.toString().split("\n".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
        assertEquals("goodby $name", splitName[0].trim())
    }

    @Test
    fun oweMessagesTo_test() {
        val name = "raldes"
        val balance = 0
        messagesUtils.oweMessages(balance, name, false)
        val splitName = outputStreamCaptor.toString().split("\n".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
        assertEquals("Owed $$balance to $name", splitName[0].trim())
    }

    @Test
    fun oweMessagesFrom_test() {
        val name = "raldes"
        val balance = 0
        messagesUtils.oweMessages(balance, name, true)
        val splitName = outputStreamCaptor.toString().split("\n".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
        assertEquals("Owed $$balance from $name", splitName[0].trim())
    }

}
